stages:
  - build
  - release
build:
  stage: build
  except:
    - tags
  tags:
    - Shell
  script:
    - pwd
    - mvn clean package install deploy -U

release:
  stage: release
  tags:
    - Shell
  only:
    - tags
  script:
    - pwd
    - mvn clean
    - V_VER=$(git tag | head -n 1)
    - VER=${V_VER:1}
    - echo "准备构建 ${VER}"
    - mvn versions:set -DnewVersion=$VER -DgenerateBackupPoms=false
    - mvn clean package install deploy -U