stages:
  - build
  - release
build:
  stage: build
  only:
    - master
    - /^dev[0-9]+(?:.[0-9]+)+$/
  except:
    - tags
  tags:
    - Shell
  script:
    - pwd
    - mvn clean package install deploy -U

release:
  stage: release
  tags:
    - Shell
  only:
    - /^tags-v([0-9]+).([0-9]+).([0-9]+)/
  script:
    - pwd
    - mvn clean
    - V_VER=$(git tag | head -n 1)
    - VER=${V_VER:1}
    - echo "准备构建 ${VER}"
    - mvn versions:set -DnewVersion=$VER -DgenerateBackupPoms=false
    - mvn clean package install deploy -U