name: GitHub Actions On Tag Push
on:
  push:
    tags:
      - '*'
jobs:
  build-and-publsh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: sonatype-nexus-staging
          server-username: ${{ secrets.nexus_username }}
          server-password: ${{ secrets.nexus_password }}
          gpg-passphrase: ${{ secrets.gpg_passphrase }}

      - run: mvn versions:set -DnewVersion=${{ steps.get_tag_name.outputs.VERSION }} -DgenerateBackupPoms=false

      - name: Publish to Maven Central Repo
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}